language: java
sudo: false
deploy:
  provider: releases
  api_key:
    secure: TH8AyyzMUv8Hqu47quvoBjK0RQf41xtvsed3otUvEV0lJSAiqqogiOZVqerD2utghVPfhEGKUwzOZbwLAViElOqf7U0J6onFIwa3NGWteP9vIvtgIEUeJD7kuAJu1v9Zc2euAjzLSwYifngWrxl04I9pZZNh7BgtcdmKbsHN5zQqGFZOFJITnFFuovMQJpFgbfBtBPL+jygmSplTuaLSFjd5nW9S6GQp+DHKC6oCNIAfvAp7vNQU5CLhp6+FEgu+my8flfnFIaEDs4LTvDujWZ95u0ls/RMmZ3+x3BGPGy/D0P698uRjl0ONRcK3SBNCcIfpzJSR8EdXm+tm7oR44YMOVmQAthS1zVtE1GVRhNZCJeZ0KCBZc+RCJ8NfggjOr3372ZpAHmGDmV91PC+OqbREVgtKs3JGlxQwLpPtJ+Il0sMir+B4RoM2Kc8KzNCEI6I49XGeoTprM0sbvw7TaVhplji0YmofL5KYm39XdTsMbCq4GkLM/Chr+5tCzEc4W1JxT+38kJLMlVS44w+kDPqTBw+msLqthJd6YDZpnBy+nm9rw098MfC2aNNfO063/RQgovUxuyVZ5n28/Am8KzhJ0UDdDtdI9KBDgH6+XW/4iErSDPWltxIuFdPZSxJSr13yeCbPhgJ2BqxJcMBd+E/+wmWxj2Y/wu51AHa4vEo=
  file: build/libs/xlr-neotys-plugin-1.2.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-neotys-plugin
notifications:
  slack:
    secure: CdekBlqU+92YdEFSxLdnDuI8FhmtGmxuGPd2SYGzyffjeEmArKowoq4xZhagBYelkZHq3l33UtECAnvVEsVJmWiGg4kF4Zwq6fQpHugqEDELH9zc7w29Wgz/QJwViGxnx3BYb4uJW8+6kIwJ+4YVg0THOzxDd2n48mH6XRwrS166TTGkY/vRzF/tDqmCFOFSHdwVwnfqtkM9kwWGneeIEko+gP9SMSlZajX9iNIAlEKyS2NBgNQkwZqQnTG6COBH3nboSGZ5Z48qWQ3IkLU7gyasSUOYQPlS3KIb6iLa0MYWi8GVlERQcXoi1d5+xDvycYKJP2cPGKzyB3N0Q8MRE3mAnd/ZAOASTUyIn3TrAr1LW4y4UMGlNU4MI/BVqzowYB7RmY1dwW+ptkg0ZtS95aL+OM5oKaYXapA6CDpqo1kx4cgQTAcP/ijZV1ZJSHGzegAEDSt9Dy1K3dHHRvIFdrDcenmA0c5KDegYXp81vZoQ2kN8q1oUnWfvb7AZkf7AzQ0BMjzTCdc0qvsy2ShXIJXrHjGlzfTwFN1xF1ZBCPXfXihHmP0kqwfF91sPVejCabBljQ3Rnk1Kh9uqwmcQrWk1Beb2yL16waKjMdUe0w3vqYs2kDc8n/b4rkO1ZQ02mOl4+oeofNUplHUaTgycR4gPbRlNCNyZnP4rWHeBGV8=
